### ISSUE TITLE
This is an FYI - 3 resets required before OS launches fully.

### ISSUE THREAD

**Issue by LostAccount** [ranma42/TigerOnVBox#6]
Hello

I am running Mac OS High Sierra 10.13.5

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir6,2
  Processor Name:	Intel Core i5
  Processor Speed:	1,3 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Memory:	4 GB
  Boot ROM Version:	MBA61.0107.B00
  SMC Version (system):	2.13f15

Virtual Box version 5.2.12 r122591 (Qt5.6.3)

Running Mac OS X 10.4.11 server in VBox

**ISSUE**
I noticed that I have to reset 3 times before Mac OS X 10.4.x will load to the desktop. This is an FYI

Best regards
—Alex

**Comment by kencu** [comment]
For this reason I usually don't shut down Tiger in VirtualBox, but suspend it and save the state. Every once in a while I do reboot, just for "cleanliness".

Also, perhaps for this reason, I have to specifically set the clock every time I relaunch it using the System Preferences date and time panel, using "Network Time".

That minor issue aside, @ranma42 has done a really spectacular job here. It is quite helpful to have Tiger Intel working to help move build fixes along with Tiger PPC (and to have people without PPC boxes try out Tiger builds if they want to).
